# Generated by Django 5.2.4 on 2025-10-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelgroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group_images/'),
        ),
    ]
